### ISSUE TITLE
Hook the internal/parser/parse_cli.go with cmd/main.go

### ISSUE THREAD

**Issue by jmaister** [rog-golang-buddies/go-automatic-apps#11]
Use `internal/parser/parse_cli.go` in `cmd/main.go` to route the to different functions of the application depending on the commands and flags.

**Comment by jmaister** [comment]
As a starting point, we can create the "help" and "version" commands.

help: shows the available commands
version: print the go version, go architecture, and GAA version

**Comment by whutchinson98** [comment]
I'd like to take this on if that is alright with you

**Comment by jmaister** [comment]
The go version can be seen here: https://pkg.go.dev/runtime

    runtime.Version()
    runtime.GOOS
    runtime.ARCH
