### ISSUE TITLE
Investigate whether we should use gRPC or traditional REST

### ISSUE THREAD

**Issue by whutchinson98** [rog-golang-buddies/go-automatic-apps#13]
gRPC is a new way of creating backends that effectively allows you to simply call a "function" that is like a traditional REST call

More information on it can be found here [Quick start guide](https://grpc.io/docs/languages/go/quickstart/)

A huge benefit to gRPC is the speed compared to traditional REST. It also would still allow us to use  [a rest gateway](https://github.com/grpc-ecosystem/grpc-gateway) to still have a rest api layer when the service is running. This imo is the best of both worlds as it allows for speed for those who want to use gRPC but still has the convenience of REST if you are just doing something quick

**Comment by jmaister** [comment]
How the UI would call the gRPC API?

**Comment by whutchinson98** [comment]
> How the UI would call the gRPC API?

https://www.freecodecamp.org/news/how-to-use-grpc-web-with-react-1c93feb691b5

There are libraries that can be used to interact with the protobufs (the function definitions) to call the service

**Comment by whutchinson98** [comment]
I don't know if performance or future proofing (I do believe that rpc is the future, especially with trpc [typescript rpc] rising in popularity rapidly) is something we want/need to worry about. If it isn't a big concern I think just sticking with REST is fine. I just figured it's worth exploring this option as it is becoming very mainstream to use rpc instead of REST lately

**Comment by arnevm123** [comment]
I was thinking that using gRPC might make this project less of a clone of Django, which seems like a plus for me. Not sure if this is worth considering

**Comment by whutchinson98** [comment]
I think we should create an issue then to re-setup the `server` portion of the application to be done in gRPC.

**Comment by jmaister** [comment]
Can gRPC and HTTP servers co-exist? I am going to start developing the UI that will be served by HTTP, using [Gin Gonic](https://gin-gonic.com/)
The server side is not developed yet, so it can be started using any technology.

**Comment by whutchinson98** [comment]
> Can gRPC and HTTP servers co-exist? I am going to start developing the UI that will be served by HTTP, using [Gin Gonic](https://gin-gonic.com/) The server side is not developed yet, so it can be started using any technology.

They can co-exist but it is very unideal to use both as it would mean a lot of code duplication. I think the best approach if we are to use gRPC is to use https://github.com/grpc-ecosystem/grpc-gateway in order to create rest endpoints.

Otherwise I think it is not worth doing gRPC

**Comment by jmaister** [comment]
> > Can gRPC and HTTP servers co-exist? I am going to start developing the UI that will be served by HTTP, using [Gin Gonic](https://gin-gonic.com/) The server side is not developed yet, so it can be started using any technology.
> 
> They can co-exist but it is very unideal to use both as it would mean a lot of code duplication. I think the best approach if we are to use gRPC is to use https://github.com/grpc-ecosystem/grpc-gateway in order to create rest endpoints.
> 
> Otherwise I think it is not worth doing gRPC

I mean to use HTTP to server the app (only HTML/JS/CSS) and use gRPC for the API.

**Comment by wralith** [comment]
Do we have any plan to generate micro services, what are we planning to use gRPC for?

**Comment by jmaister** [comment]
Let's go with gRPC!!!
