### ISSUE TITLE
protoc build error

### ISSUE THREAD

**Issue by jmaister** [rog-golang-buddies/go-automatic-apps#30]
I get this error on `make protoc`. I am working on Windows, and I already installed the protoc executable.

protoc version: protoc-21.4-win64

@segfault99 do you have any idea about this?

```
PS C:\workspace\go-automatic-apps> make protoc
protoc -I=./proto --go_out=. --go-grpc_out=. ./proto/*.proto
'protoc-gen-go-grpc' is not recognized as an internal or external command,
operable program or batch file.
--go-grpc_out: protoc-gen-go-grpc: Plugin failed with status code 1.
make: *** [Makefile:40: protoc] Error 1
```

**Comment by segfault99** [comment]
@jmaister 
You need to install go plugins
`go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28`
`go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2`
