### ISSUE TITLE
Read the list of available models with ent

### ISSUE THREAD

**Issue by jmaister** [rog-golang-buddies/go-automatic-apps#4]

**Comment by amanangira** [comment]
Hello @jmaister , what are your thoughts on the following? 

- Having a configurable path where all models/structs representing the DB tables would exists. 
- This configuration file would be utilised by the GAA CLI to feed in all the models. 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by jmaister** [comment]
I started implementing this on this branch: https://github.com/rog-golang-buddies/go-automatic-apps/tree/start-library

The final idea is that the models are defined using `ent`, we will save all the schema definition, schema migration, etc...

**Comment by jmaister** [comment]
Done on #6
